Importation of modules

In [1]:
import os
# import matplotlib.pylab as plt
import numpy as np
import xarray as xr
# from scipy import signal
from obspy.signal.filter import bandpass

Specific modules

In [2]:
from tools_pcc import *

In [3]:
from stack_functions_new import *

In [4]:
from xdas.io.febus import read as read_das
from xdas.io.febus import correct_gps_time

Paths

In [5]:
user = "mba"

if user == "ipgp" :
    path1 = "/home/hugonnet/Documents/DAS-Lucie/fichiers-nc/"

elif user == "mba" :
    path1 = "/Volumes/DISKENOIR/fichiers-nc/"
    path2 = "/Volumes/DISKENOIR/Correlograms/Cross-correlation/" # storage of correlograms for cross-correlation
    path3 = "/Volumes/DISKENOIR/Correlograms/Auto-correlation/" # storage of correlograms for auto-correlation

elif user == "eleonore" :
    path1 = '/Users/stutz/DAS/DAS_STROMBOLI/2022_STROMBOLI_MANIP/SILIXA_iDAS/DATA_VLP_FEBUS/'

In [6]:
file_name = 'SR_FEBUS_STROMBOLI_2022-09-18_17-35-44_UTC.nc'

Definition of the parameters

In [7]:
corr_type = 'phase-cross'   # can be 'phase-cross' (cross-correlation), 'phase-auto' (auto-correlation), 'normal', or 'onebit'

# define variable for correlation
window = 300 			# duration of time window in second
lag = window/2 			# shift of starting time on the next iteration
time = 0 			# time initialization

# filter boundary (Hz)
lowcut = 1
highcut = 10

start = 100		# starting/reference point. currently used: 100, 200, 320, 400
channel = 150		# number of channel used			 
start_position = 'mid_all' 

change_gauge_length = False
gauge_length = 50

In [8]:
if corr_type == 'phase-cross' :
    folder_destination = path2 + file_name.replace(".nc", "/") # please make the folder before running

elif corr_type == 'phase-auto' :
    folder_destination = path3 + file_name.replace(".nc", "/") # please make the folder before running

In [9]:
ds = xr.open_dataset(path1 + file_name)
channels_coord = ds['channels']

In [10]:
ds

<xarray.Dataset>
Dimensions:       (times: 180000, offsets: 3250, channels: 3250)
Coordinates:
  * times         (times) datetime64[ns] 2022-09-18T17:35:44.500000 ... 2022-...
  * offsets       (offsets) float64 0.0 2.0 4.0 ... 6.496e+03 6.498e+03
  * channels      (channels) float64 0.0 1.0 2.0 ... 3.248e+03 3.249e+03
Data variables:
    strain_rates  (times, offsets) float32 ...
Attributes:
    unit:     strain rates in 10e-8 /s

In [11]:
iDas_nc = xr.DataArray(
    data=ds['strain_rates'],  # Remplacez par les données réelles de 'strain_rates'
    dims=("times", "channels"),  # Spécifiez les dimensions
    coords={"times": ds['strain_rates'].coords["times"], "channels": channels_coord},
)

In [12]:
iDas_nc

<xarray.DataArray 'strain_rates' (times: 180000, channels: 3250)>
array([[ 0.0000000e+00,  0.0000000e+00, -3.4953697e-08, ...,
         4.4692129e+03, -8.0042388e-05,  5.1425472e-05],
       [ 0.0000000e+00,  0.0000000e+00,  6.1442131e-09, ...,
         2.8822549e+03, -5.6834502e-05,  3.3164910e-05],
       [ 0.0000000e+00,  0.0000000e+00, -1.7207492e-08, ...,
         3.8322634e+03, -7.1476410e-05,  4.4096316e-05],
       ...,
       [ 0.0000000e+00, -8.2707105e-12,  1.3172808e-08, ...,
         1.0095570e+02, -1.7541629e-06,  1.1616555e-06],
       [ 0.0000000e+00,  0.0000000e+00,  7.6554487e-09, ...,
         9.9110550e+01, -1.7135526e-06,  1.1404245e-06],
       [ 0.0000000e+00,  0.0000000e+00, -3.6883813e-10, ...,
         9.9572304e+01, -1.7854875e-06,  1.1457379e-06]], dtype=float32)
Coordinates:
  * times     (times) datetime64[ns] 2022-09-18T17:35:44.500000 ... 2022-09-1...
  * channels  (channels) float64 0.0 1.0 2.0 ... 3.247e+03 3.248e+03 3.249e+03

Time step (dt) and sampling rate (fs)

In [13]:
dt = ( iDas_nc['times'][1].item() - iDas_nc['times'][0].item() ) * 1e-9 # s
fs = 1/dt # Hz

Output array

In [14]:
# make output array
if start_position == 'mid':
	#cc_normal = np.zeros((2*int(window/dt),2*channel+1))
	#cc_onebit = np.zeros((2*int(window/dt),2*channel+1))
	cc_phase = np.zeros((2*int(window/dt),2*channel+1))
elif start_position == 'mid_all':
	#cc_normal = np.zeros((2*int(window/dt),430+1))
	#cc_onebit = np.zeros((2*int(window/dt),430+1))
	cc_phase = np.zeros((2*int(window/dt),430+1)) # change to 100-57+1 if only want from 57 to 100
	#cc_phase = np.zeros((2*int(window/dt),3249+1))
else:
	#cc_normal = np.zeros((2*int(window/dt),channel+1))
	#cc_onebit = np.zeros((2*int(window/dt),channel+1))
	cc_phase = np.zeros((2*int(window/dt),channel+1))

Correlation

In [15]:
f = open('error.txt','w') # files with few channels are not used and are stored into the file 'f'

if iDas_nc.shape[1] < 463: 
    print(f'This file only has {iDas_nc.shape[1]} channels. Skipping this file')
    f.write(f'{iDas_nc.shape[1]} channels\n')
	# skipping file if the channel is not complete

else :

    print(f'Filtering using bandpass filter between {lowcut} and {highcut} Hz ...')

    if change_gauge_length == False:
        traces_filt = iDas_nc.copy()
        print('no gauge length change')
    else:
        
        # to try GL = 10
        traces_filt = iDas_nc.copy()
        traces_filt[:,0] = iDas_nc[:,0] + iDas_nc[:,1] # the first channel with gl = 10 is defined as channel 0 + channel 1
        traces_filt[:,-1] = iDas_nc[:,-2] + iDas_nc[:,-1] # the last channel with gl = 10 is defined as channel N-1 + channel N
        print(f'Converting data to using gauge length = 10')
        #for i in range(1,traces_filt.shape[1]-2): # each end is skipped because it has been calculated in the previous line
        for i_channel in range(57, iDas_nc['channels'].values[-2]+1):
            traces_filt[:,i_channel] = iDas_nc[:,i_channel-1] + iDas_nc[:,i_channel] + iDas_nc[:,i_channel+1]
        traces_filt_gl10 = traces_filt[::2]

## à modifier ??? c'est les channels qu'on veut modifier ou les strain rates ? (au-dessus)

    #for j in [56,3249]:
    for j in [57,430]:
        try:
            #traces_filt[:,j] = filter_bandpass(iDas_nc[:,j], lowcut, highcut, fs,order=4) # filter defined in stack_functions and using scipy.signal.butter filter
            traces_filt[:,j] = bandpass(iDas_nc[:,j],lowcut,highcut,fs, zerophase=True) # obspy butterworth filter (faster)
        except:
            print('filtrage pas abouti pour j = ', j)
            #None
		
    length = iDas_nc.shape[0]	# total length of data

	# cross correlate

    if corr_type == 'phase-cross' :
        print('\nStarting the phase cross-correlation  ...')
        cc_phase, t = cross_correlate(cc_phase,traces_filt,folder_destination,window,lag,length,time,channel,
                                      start,start_position,onebit=False,phase_cc=True,decimate=1,resample=1)

    elif corr_type == 'phase-auto' :
        print('\nStarting the phase auto-correlation  ...')
        cc_phase_auto, t = auto_correlate(cc_phase,traces_filt,folder_destination,window,lag,length,time,channel, 
                                          start,start_position,onebit=False,phase_cc=True,decimate=1,resample=1)


    #print('\nStarting the normal cross-correlation  ...')
    #cc_normal, t = cross_correlate(cc_normal,traces_filt,window,lag,length,time,channel,
    #		start,start_position,onebit=False,phase_cc=False,decimate=decimate,resample=resample)

    #cc_onebit, t = cross_correlate(cc_onebit,traces_filt,window,lag,length,time,channel,
    #		start,start_position,onebit=True,phase_cc=False,decimate=decimate,resample=resample)


f.close()

Filtering using bandpass filter between 1 and 10 Hz ...
no gauge length change

Starting the phase cross-correlation  ...
Start of the 1th time window. Starttime = 0.0 s
Start of the 2th time window. Starttime = 150.0 s
Start of the 3th time window. Starttime = 300.0 s
Start of the 4th time window. Starttime = 450.0 s
Start of the 5th time window. Starttime = 600.0 s
Start of the 6th time window. Starttime = 750.0 s
Start of the 7th time window. Starttime = 900.0 s
Start of the 8th time window. Starttime = 1050.0 s
Start of the 9th time window. Starttime = 1200.0 s
Start of the 10th time window. Starttime = 1350.0 s
Start of the 11th time window. Starttime = 1500.0 s
Start of the 12th time window. Starttime = 1650.0 s
Start of the 13th time window. Starttime = 1800.0 s
Start of the 14th time window. Starttime = 1950.0 s
Start of the 15th time window. Starttime = 2100.0 s
Start of the 16th time window. Starttime = 2250.0 s
Start of the 17th time window. Starttime = 2400.0 s
Start of the

In [16]:
cc_phase

array([[-4.66666656e-04, -5.71208970e-04, -5.99999999e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.00000363e-04, -6.60304994e-04, -1.19999956e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.26666323e-03, -7.22319720e-04, -1.80000217e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-8.00000275e-04, -8.30355084e-04, -1.19999875e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.33333431e-04, -4.66666713e-04, -6.00000037e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.75267208e-17, -1.27897692e-17, -5.32907052e-18, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [18]:
cc_phase_auto

array([[ 1.53333333e-03,  1.53333333e-03,  1.40000003e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.06666644e-03,  3.06666641e-03,  3.06666563e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 4.59999939e-03,  4.59999891e-03,  4.20002470e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [ 3.06666644e-03,  3.06666641e-03,  3.06666563e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 1.53333333e-03,  1.53333333e-03,  1.40000003e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.71850698e-17, -2.55795385e-17,  2.20268248e-17, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

tf-PWS (time-frequency domain Phase Weighted Stack)

In [ ]:
if corr_type == 'phase-cross' :
    folder = path2 + file_name.replace(".nc", "/")

elif corr_type == 'phase-auto' :
    folder = path3 + file_name.replace(".nc", "/")

In [ ]:
for i_channel in range(57,430):
#for i in range(100,103):

	os.system(f'cp /home/mozef/Documents/scripts/ts_pws {folder}/Correlogram_{start}_{i_channel}_phase/')
	os.chdir(f'{folder}/Correlogram_{start}_{i_channel}_phase/')
	os.system('find . -type f -empty -print -delete') # delete empty file
	print(f'tf-pws for correlogram {start} and {i_channel}')
	os.system('ls *.sac > tf-pws.in')
	os.system('./ts_pws tf-pws.in osac="tspws_pcc"')
	# there will be a warning that says the header is corrupted, just ignore it since we just need the cross-correlogram time array, the header information is not important
